In [44]:
import numpy as np
revenu = [1200 , 1500 , 1800 , 2000]
revenu_array = np.array(revenu) #creation d'un array
np.mean(revenu_array) #calculer la moyenne de ce tableau
#acces au elements d'un array
print(revenu_array[1])
print(revenu_array[-1])
print(revenu_array[:3])
print(revenu_array[2:])
print(revenu_array[::3])
print(revenu_array[::-1])
revenu_array[(revenu_array>1200) & (revenu_array<2000)]
revenu_array.shape
revenu_array.max()
revenu_array.min()



1500
2000
[1200 1500 1800]
[1800 2000]
[1200 2000]
[2000 1800 1500 1200]


1200

In [51]:
# fonction de creation d'un array selon des criteres
np.zeros(3)
np.ones(3)
np.arange(1,10,2)
np.linspace(5, 10, 11)
a = np.linspace(5, 10, 11)
print(a[-3:-1])

[9.  9.5]


In [47]:
#exercice
liste = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]

revenu  = np.array(liste)
haut_revenu = revenu[revenu>=3000]
somme = revenu.sum()*12
moyenne = revenu.mean()
revenu[revenu==1400]+=200
revenu

array([1800, 1500, 2200, 3000, 2172, 5000, 1600, 1200, 1100, 1300])